name: CI

on:
  push:
    branches-ignore:
      - 'task/**'
      - 'bugfix/**'
      - 'feature/**'
  pull_request:

jobs:

  build-php:
    name: Build PHP
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        bootstrap-package: ['^12', '^13', '^14']
        php: ['8.2']
        mysql: ['8.0']

    steps:
      - id: checkout
        name: Checkout Code
        uses: actions/checkout@v3
      - id: setup_mysql
        name: Set up MySQL ${{ matrix.mysql }}
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: ${{ matrix.mysql }}
          mysql root password: 'root'
      - id: setup_php
        name: Set up PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
      - name: Composer Cache Vars
        id: composer-cache-vars
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
          echo "timestamp=$(date +"%s")" >> $GITHUB_OUTPUT
      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache-vars.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ matrix.php }}-${{ matrix.typo3 }}-${{ steps.composer-cache-vars.outputs.timestamp }}
          restore-keys: |
            ${{ runner.os }}-composer-${{ matrix.php }}-${{ matrix.typo3 }}-
            ${{ runner.os }}-composer-${{ matrix.php }}-
            ${{ runner.os }}-composer-
      - id: install
        name: Install
        run: |
          composer require bk2k/bootstrap-package:${{ matrix.bootstrap-package }} --no-progress
          git checkout composer.json
      - id: lint
        name: Lint
        if: ${{ always() && steps.install.conclusion == 'success' }}
        run: |
          composer test:php:lint
      - id: cgl
        name: CGL
        if: ${{ always() && steps.install.conclusion == 'success' }}
        run: |
          composer cgl:ci
        env:
          PHP_CS_FIXER_IGNORE_ENV: true
      - id: phpstan
        name: PHPStan
        if: ${{ always() && steps.install.conclusion == 'success' }}
        run: |
          composer phpstan -- --error-format=github

  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install
        run: |
          npm ci
      - name: Build
        run: |
          npm run build
      - name: Status
        run: |
          git status
          git status | grep -q "nothing to commit, working tree clean"
